In [2]:
import numpy as np
from scipy import linalg

In [38]:
A = np.random.randint(20, size=(3,3))
A

array([[13, 19,  7],
       [ 2, 15,  6],
       [14, 10, 15]])

In [39]:
# Inverse of matrix :
linalg.inv(A)

array([[ 0.0896252 , -0.11678436,  0.00488865],
       [ 0.02933188,  0.05268876, -0.03476372],
       [-0.10320478,  0.0738729 ,  0.08527974]])

In [12]:
# Dot product of two arrays :
A.dot(linalg.inv(A)) 

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.08166817e-17],
       [ 0.00000000e+00,  3.46944695e-18,  1.00000000e+00]])

**Solving Linear System :**

In [15]:
B = np.array([3,2,5])
B

array([3, 2, 5])

In [16]:
linalg.inv(A).dot(B) # slow proc.

array([ 3.        , -0.44897959, -1.78911565])

In [17]:
linalg.solve(A,B) # fast proc.

array([ 3.        , -0.44897959, -1.78911565])

**Eigen Values - Eigen Vectors :**

In [24]:
eigvalue, eigvector = linalg.eig(A)
print(eigvalue,"\n", eigvector)

[21.+0.j 14.+0.j  1.+0.j] 
 [[ 0.          0.          0.80214827]
 [ 0.6         0.70710678 -0.14191854]
 [ 0.8        -0.70710678 -0.5800149 ]]


**Singular Value Decomposition (SVD) :**

can be thought of as an extension of the eigenvalue problem to matrices that are not square.

In [32]:
A = np.random.randint(20, size=(2,3))
M,N = A.shape
linalg.svd(A) # we have 3 arrays

(array([[-0.76451416, -0.64460693],
        [-0.64460693,  0.76451416]]),
 array([29.53179205,  4.45794328]),
 array([[-0.15126673, -0.85887709, -0.48933477],
        [-0.55149209,  0.48415381, -0.67930225],
        [-0.82035044, -0.16710842,  0.54690029]]))

In [34]:
# U :Unitary matrix having left singular vectors as columns. (ndarray)
# s :The singular values, sorted in non-increasing order. (ndarray)
# Vh:Unitary matrix having right singular vectors as rows. (ndarray)

U, s, Vh = linalg.svd(A)

In [35]:
# Construct the sigma matrix in SVD from singular values and size MxN
sig = linalg.diagsvd(s,M,N)
sig

array([[29.53179205,  0.        ,  0.        ],
       [ 0.        ,  4.45794328,  0.        ]])

In [37]:
#check computation
U.dot(sig.dot(Vh))

array([[ 5., 18., 13.],
       [ 1., 18.,  7.]])